### ISSUE TITLE
upload xml Error

### ISSUE THREAD

**Issue by itmuji** [fredsdc/redmine_import_xml#1]
An error occurs when uploading an xml file in an issue.
I definitely need a way to upload xml. help

my version
Redmine version                4.1.1.stable
Ruby version                   2.6.3-p62 (2019-04-16) [x86_64-linux]
Rails version                  5.2.4.2

```
plugins/redmine_import_xml/lib/redmine_import_xml/patches/imports_controller_patch.rb:33:in `settings'
lib/redmine/sudo_mode.rb:65:in `sudo_mode'
Started POST "/imports" for 10.XX.XX.XX at 2023-11-10 00:36:52 +0000
Processing by ImportsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"bHo31VZuIT8QYz1b/XOwMW+kpZIUxWwdcNoXFd2ITW+pJPF+K3MIlCBac4pc98fLivV4R0CqgxD8k6diWvxnLQ==", "type"=>"IssueImport", "project_id"=>"jira-to-redmine-project", "file"=>#<ActionDispatch::Http::UploadedFile:0x00007f23a11b36b0 @tempfile=#<Tempfile:/tmp/RackMultipart20231110-67158-1qivdj0.xml>, @original_filename="130452.xml", @content_type="text/xml", @headers="Content-Disposition: form-data; name=\"file\"; filename=\"130452.xml\"\r\nContent-Type: text/xml\r\n">}
  Current user: XXX_XXXXXX (id=6)
Redirected to https://redmine4.xxxxx.com/imports/a43a88b5f98db1ccdc6df4c6e88bab6a/settings
Completed 302 Found in 12ms (ActiveRecord: 3.6ms)
Started GET "/imports/a43a88b5f98db1ccdc6df4c6e88bab6a/settings" for 10.XX.XX.XX at 2023-11-10 00:36:52 +0000
Processing by ImportsController#settings as HTML
  Parameters: {"id"=>"a43a88b5f98db1ccdc6df4c6e88bab6a"}
  Current user: XXX_XXXXXX (id=6)
Completed 500 Internal Server Error in 102ms (ActiveRecord: 1.7ms)

NoMethodError (undefined method `[]' for nil:NilClass):

plugins/redmine_import_xml/lib/redmine_import_xml/patches/imports_controller_patch.rb:33:in `settings'
lib/redmine/sudo_mode.rb:65:in `sudo_mode'
```

**Comment by fredsdc** [comment]
Vanilla Redmine already allows you to upload any file to an issue (if you have the permission)

This plugin have so little documentation it can be deceptive. It was meant to recover an issue from a xml backup, exported using the REST api. For example, let's have the issue #1 from redmine at your.redmine.com, look at the xml from https://your.redmine.com/issues/1.xml?include=journals. If someone deletes this issue there's a long way looking at logs to recover it. This plugin imports the issue xml file and recreates the issue, including the journals if the backup has it. It cannot recover attached files, though.

**Comment by fredsdc** [comment]
To import a xml file to an issue. Send the file as if any other file (Select the issue > Edit, roll down, Add File)

**Comment by fredsdc** [comment]
Closing issue
